name: gym_env
channels:
- defaults
dependencies:
- ca-certificates=2017.08.26
- certifi=2017.7.27.1
- libedit=3.1
- libffi=3.2.1
- libgcc-ng=7.2.0
- libstdcxx-ng=7.2.0
- ncurses=6.0
- openssl=1.0.2m
- pip=9.0.1
- python=3.6.3
- readline=7.0
- setuptools=36.5.0
- sqlite=3.20.1
- tk=8.6.7
- wheel=0.29.0
- xz=5.2.3
- zlib=1.2.11
- pip:
  - atari-py==0.1.1
  - box2d-kengz==2.3.3
  - chardet==3.0.4
  - idna==2.6
  - imageio==2.2.0
  - keras==2.0.9
  - mujoco-py==0.5.7
  - numpy==1.13.3
  - olefile==0.44
  - pachi-py==0.0.21
  - pillow==4.3.0
  - pyglet==1.2.4
  - pyopengl==3.1.0
  - pyyaml==3.12
  - requests==2.18.4
  - scipy==1.0.0
  - six==1.11.0
  - theano==0.9.0
  - urllib3==1.22

